title: flowerJun
description: Development Blog of the flowerJun

url: https://flowerjun.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: flowerJun
   twitter:
   facebook:
   email: junho2451@icloud.com

google_analytics: "UA-58263416-1"
